Importacao de Bibliotecas e Carregamento dos Dados

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import mannwhitneyu

# Carregamento dos dados
df_events = pd.read_csv('final_ab_events_upd_us.csv')
df_users = pd.read_csv('final_ab_new_users_upd_us.csv')
df_participants = pd.read_csv('final_ab_participants_upd_us.csv')
df_marketing = pd.read_csv('ab_project_marketing_events_us.csv')

PRÉ PROCESSAMENTO DE DADOS

In [ ]:
# df_events

df_events.describe()

            details
count  60314.000000
mean      23.881219
std       72.228884
min        4.990000
25%        4.990000
50%        4.990000
75%        9.990000
max      499.990000

In [ ]:
print(df_events.shape)
df_events.info()
print(df_events.sample(15))

(423761, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423761 entries, 0 to 423760
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   user_id     423761 non-null  object
 1   event_dt    423761 non-null  object
 2   event_name  423761 non-null  object
 3   details     60314 non-null   float64
dtypes: float64(1), object(3)
memory usage: 12.9+ MB
                 user_id             event_dt    event_name  details
166820  AC46ACF2B454A5F4  2020-12-16 11:04:35  product_page      NaN
289142  929B21986BE0CFE9  2020-12-14 22:24:53         login      NaN
303937  6109B4A3712F0757  2020-12-15 09:21:15         login      NaN
19971   DF483D2AA71EBB26  2020-12-15 08:01:47      purchase     4.99
43306   4C0A4AD94F5495D4  2020-12-22 03:37:04      purchase     4.99
97838   3A9057CD58DF721B  2020-12-20 00:28:32  product_cart      NaN
139327  EF3BA2CE7CD7762A  2020-12-12 09:47:17  product_page      NaN
370943  1738843E589984B4  2020-12-22 15:46:48         login      NaN
408015  6B316C103724A29C  2020-12-26 22:31:56         login      NaN
135536  B79DB04DA8397B3B  2020-12-11 05:51:08  product_page      NaN
258823  8982354F48EA7862  2020-12-10 21:31:58         login      NaN
230519  6B6C5ED11777C125  2020-12-26 17:37:09  product_page      NaN
356314  4CF9452FB5DB9064  2020-12-20 02:30:12         login      NaN
235100  BF205E3B70E8EB4A  2020-12-27 14:38:43  product_page      NaN
350293  DAA2BD88ED9E296A  2020-12-20 18:17:03         login      NaN

O df_events apresenta muitos NaNs em details, isso é causado por causa que nem todos clientes efetuaram uma compra

In [ ]:
# df_users

df_users.describe()

                 user_id  first_date region   device
count              58703       58703  58703    58703
unique             58703          17      4        4
top     8F04273BB2860229  2020-12-21     EU  Android
freq                   1        6077  43396    26159

In [ ]:
print(df_users.shape)
df_users.info()
print(df_users.head(15))
print(df_users['device'].unique())

(58703, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58703 entries, 0 to 58702
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     58703 non-null  object
 1   first_date  58703 non-null  object
 2   region      58703 non-null  object
 3   device      58703 non-null  object
dtypes: object(4)
memory usage: 1.8+ MB
             user_id  first_date     region   device
0   D72A72121175D8BE  2020-12-07         EU       PC
1   F1C668619DFE6E65  2020-12-07  N.America  Android
2   2E1BF1D4C37EA01F  2020-12-07         EU       PC
3   50734A22C0C63768  2020-12-07         EU   iPhone
4   E1BDDCE0DAFA2679  2020-12-07  N.America   iPhone
5   137119F5A9E69421  2020-12-07  N.America   iPhone
6   62F0C741CC42D0CC  2020-12-07       APAC   iPhone
7   8942E64218C9A1ED  2020-12-07         EU       PC
8   499AFACF904BBAE3  2020-12-07  N.America   iPhone
9   FFCEA1179C253104  2020-12-07         EU  Android
10  5EB159DA9DC94DBA  2020-12-07       APAC       PC
11  084A22B980BA8169  2020-12-07         EU  Android
12  8ACC2420471B31E4  2020-12-07         EU       PC
13  5BE017E9C8CC42F8  2020-12-07         EU  Android
14  7B6452F081F49504  2020-12-07         EU   iPhone
['PC' 'Android' 'iPhone' 'Mac']

A coluna DEVICE tem somente 4 possibilidades para 58mil entradas, vou substituir o dtype para categorico

In [ ]:
# df_participants

df_participants.describe()

                 user_id  group            ab_test
count              14525  14525              14525
unique             13638      2                  2
top     FABB6D49B11E673F      A  interface_eu_test
freq                   2   8214              10850

In [ ]:
print(df_participants.shape)
df_participants.info()
print(df_participants.head(15))

(14525, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14525 entries, 0 to 14524
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  14525 non-null  object
 1   group    14525 non-null  object
 2   ab_test  14525 non-null  object
dtypes: object(3)
memory usage: 340.6+ KB
             user_id group                  ab_test
0   D1ABA3E2887B6A73     A  recommender_system_test
1   A7A3664BD6242119     A  recommender_system_test
2   DABC14FDDFADD29E     A  recommender_system_test
3   04988C5DF189632E     A  recommender_system_test
4   4FF2998A348C484F     A  recommender_system_test
5   7473E0943673C09E     A  recommender_system_test
6   C46FE336D240A054     A  recommender_system_test
7   92CB588012C10D3D     A  recommender_system_test
8   B3A2485649E4A012     A  recommender_system_test
9   66FC298441D50783     A  recommender_system_test
10  CD74C3D22FFC09C2     B  recommender_system_test
11  19F4A16B875E04EE     A  recommender_system_test
12  80A2F277C571443C     A  recommender_system_test
13  50AA023EF325BCA1     B  recommender_system_test
14  C716AF018B3D96F5     A  recommender_system_test

In [ ]:
# df_marketing

df_marketing.describe()

                            name regions    start_dt   finish_dt
count                         14      14          14          14
unique                        14       6          14          14
top     Christmas&New Year Promo    APAC  2020-12-25  2021-01-03
freq                           1       4           1           1

In [ ]:
print(df_marketing.shape)
df_marketing.info()
print(df_marketing.head(15))

(14, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       14 non-null     object
 1   regions    14 non-null     object
 2   start_dt   14 non-null     object
 3   finish_dt  14 non-null     object
dtypes: object(4)
memory usage: 576.0+ bytes
                                name                   regions    start_dt  \
0           Christmas&New Year Promo             EU, N.America  2020-12-25
1       St. Valentine's Day Giveaway  EU, CIS, APAC, N.America  2020-02-14
2             St. Patric's Day Promo             EU, N.America  2020-03-17
3                       Easter Promo  EU, CIS, APAC, N.America  2020-04-12
4                  4th of July Promo                 N.America  2020-07-04
5          Black Friday Ads Campaign  EU, CIS, APAC, N.America  2020-11-26
6             Chinese New Year Promo                      APAC  2020-01-25
7   Labor day (May 1st) Ads Campaign             EU, CIS, APAC  2020-05-01
8    International Women's Day Promo             EU, CIS, APAC  2020-03-08
9    Victory Day CIS (May 9th) Event                       CIS  2020-05-09
10         CIS New Year Gift Lottery                       CIS  2020-12-30
11     Dragon Boat Festival Giveaway                      APAC  2020-06-25
12           Single's Day Gift Promo                      APAC  2020-11-11
13             Chinese Moon Festival                      APAC  2020-10-01

     finish_dt
0   2021-01-03
1   2020-02-16
2   2020-03-19
3   2020-04-19
4   2020-07-11
5   2020-12-01
6   2020-02-07
7   2020-05-03
8   2020-03-10
9   2020-05-11
10  2021-01-07
11  2020-07-01
12  2020-11-12
13  2020-10-07

Conversao de Tipos de Dados

In [ ]:
df_events['event_dt'] = pd.to_datetime(df_events['event_dt'])
df_users['first_date'] = pd.to_datetime(df_users['first_date'])
df_marketing['start_dt'] = pd.to_datetime(df_marketing['start_dt'])
df_marketing['finish_dt'] = pd.to_datetime(df_marketing['finish_dt'])
df_users['device'] = df_users['device'].astype('category')

print(df_events['event_dt'].dtype)
print(df_users['first_date'].dtype)
print(df_users['device'].dtype)

datetime64[ns]
datetime64[ns]
category

Valores Ausentes e Duplicados

In [ ]:
print('\nEventos:'); print(df_events.isnull().sum())
print('\nUsuarios:'); print(df_users.isnull().sum())
print('\nParticipantes:'); print(df_participants.isnull().sum())

#Há valores ausentes em details pois só é contabilizado valores aqueles que houve compras

Eventos:
user_id            0
event_dt           0
event_name         0
details       363447
dtype: int64

Usuarios:
user_id       0
first_date    0
region        0
device        0
dtype: int64

Participantes:
user_id    0
group      0
ab_test    0
dtype: int64

In [ ]:
#DUPLICADOS:
print(f'Eventos: {df_events.duplicated().sum()}')
print(f'Usuarios: {df_users.duplicated().sum()}')
print(f'Participantes: {df_participants.duplicated().sum()}')

Eventos: 0
Usuarios: 0
Participantes: 0

Distribuicao de Testes e Grupos

In [ ]:
print('Testes na base de participantes:')
print(df_participants['ab_test'].value_counts())

print('\nGrupos por teste:')
print(df_participants.groupby(['ab_test', 'group']).size().unstack(fill_value=0))

Testes na base de participantes:
ab_test
interface_eu_test          10850
recommender_system_test     3675
Name: count, dtype: int64

Grupos por teste:
group                       A     B
ab_test
interface_eu_test        5467  5383
recommender_system_test  2747   928

Verificar se há usuarios nos dois grupos

In [ ]:
df_participants['user_id'].value_counts()

user_id
FABB6D49B11E673F    2
0980BF24051C806A    2
A12886FD7DA592AF    2
8C66932374EF8009    2
DABC14FDDFADD29E    2
                   ..
D1F13A7B1FDCA67A    1
21E26F864516C019    1
D8BCC617D22C1CC5    1
71C8E038B7C82281    1
864D888038F78EE2    1
Name: count, Length: 13638, dtype: int64

In [ ]:
duplicados = df_participants['user_id'].value_counts()
duplicados = duplicados[duplicados > 1].index

df_participants = df_participants[~df_participants['user_id'].isin(duplicados)]

print(df_participants.shape)

(12751, 3)

Filtrar somente para usuários da região EU

In [ ]:
df_participants_eu = pd.merge(df_participants, df_users, on='user_id', how='left')
print(df_participants_eu.sample(10))

                user_id group                  ab_test first_date region  \
11264  3AED3907C9140ABD     B        interface_eu_test 2020-12-21     EU
6318   8B0175AA13673F0B     A        interface_eu_test 2020-12-07     EU
1103   A03EAD12BAD403BC     A  recommender_system_test 2020-12-20     EU
11305  8619A8B7D4D4279C     A        interface_eu_test 2020-12-22     EU
290    59BA4B15D73A2A6C     A  recommender_system_test 2020-12-14     EU
4440   442EF60BC0EEC963     A        interface_eu_test 2020-12-11     EU
10744  13321E5773A41579     A        interface_eu_test 2020-12-11     EU
1700   19723E02ECBEA4B8     A  recommender_system_test 2020-12-21     EU
4276   D7CBFFDE719F30B0     B        interface_eu_test 2020-12-15     EU
1757   934F4410153B7733     B  recommender_system_test 2020-12-14     EU

        device
11264  Android
6318   Android
1103       Mac
11305       PC
290    Android
4440        PC
10744  Android
1700   Android
4276    iPhone
1757   Android

In [ ]:
df_participants_eu = df_participants_eu[df_participants_eu['region'] == 'EU']
df_participants_eu.shape

(12557, 6)

In [ ]:
df_participants_eu_recomender = df_participants_eu[df_participants_eu['ab_test'] == 'recommender_system_test']
df_participants_eu_recomender.shape()